airlines = ['American Airlines',
 'Delta Air Lines',
 'United Airlines',
 'Southwest Airlines',
 'China Southern Airlines',
 'China Eastern Airlines',
 'Air China',
 'Air Canada',
 'Lion Air',
 'Alaska Airlines',
 'Shenzhen Airlines',
 'Hainan Airlines',
 'Turkish Airlines',
 'Shandong Airlines',
 'Xiamen Airlines',
 'Wizz Air',
 'Air France',
 'Sichuan Airlines',
 'British Airways',
 'Batik Air',
 'LATAM Airlines',
 'Spring Airlines',
 'Wings Air',
 'Thai AirAsia',
 'GoAir',
 'Juneyao Airlines',
 'Air New Zealand',
 'AirAsia',
 'Spirit Airlines',
 'Tianjin Airlines',
 'S7 Airlines',
 'Air India',
 'Beijing Capital Airlines',
 'Vietnam Airlines',
 'JetBlue Airways',
 'Shanghai Airlines',
 'Qatar Airways',
 'Sriwijaya Air',
 'Cebu Pacific Air',
 'Frontier Airlines',
 'Hawaiian Airlines',
 'Ethiopian Airlines',
 'Loong Air',
 'Lucky Air',
 'Chengdu Airlines',
 'Jeju Air',
 'AirAsia India',
 'Tropic Air',
 'Nam Air',
 'Cape Air',
 'Maya Island Air',
 'Malaysia Airlines',
 'Philippine Airlines',
 'China United Airlines',
 'Ural Airlines',
 'VietJet Air',
 'Skymark Airlines',
 'Allegiant Air',
 'Indonesia AirAsia',
 'Oman Air',
 'Southern Airways Express',
 'Nok Air',
 'West Air (China)',
 'Royal Air Maroc',
 'LOT - Polish Airlines']